<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Page de Connexion</title>
</head>
<body>

    <h2>Connexion</h2>

    <form action="index.php?route=check-connexion" method="post">
        <label for="loginEmail">Email:</label>
        <input type="email" id="loginEmail" name="loginEmail" required>

        <br>

        <label for="loginPassword">Mot de passe:</label>
        <input type="password" id="loginPassword" name="loginPassword" required>

        <br>

        <input type="submit" value="Se connecter">
    </form>

</body>
</html>
