<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Page d'Accueil</title>
</head>
<body>

    <h2>Accueil</h2>

    <button onclick="window.location.href='index.php?route=connexion'">Se connecter</button>
    <button onclick="window.location.href='index.php?route=inscription'">S'inscrire</button>

</body>
</html>
       