<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Page d'Inscription</title>
</head>
<body>

    <h2>Inscription</h2>

    <form action="index.php?route=check-inscription" method="post">
        <label for="signinEmail">Email:</label>
        <input type="email" id="signinEmail" name="signinEmail" required>

        <br>

        <label for="signinPassword">Mot de passe:</label>
        <input type="password" id="signinPassword" name="signinPassword" required>

        <br>

        <label for="verifPassword">Confirmer le mot de passe:</label>
        <input type="password" id="verifPassword" name="verifPassword" required>

        <br>

        <input type="submit" value="S'inscrire">
    </form>

</body>
</html>
